// src/App.tsx
import React, { useState } from "react";
import "./App.css";
import Shelf from "./components/Shelf";

interface GameItem {
  title: string;
  image: string;
  platform: string;
  genres: string[];
  finished: boolean;
}

const App: React.FC = () => {
  const [openGame, setOpenGame] = useState<string | null>(null);

  const games: GameItem[] = [
    { title: "The Legend of Zelda: Breath of the Wild", image: "/zelda.jpg", platform: "switch", genres: ["adventure", "action"], finished: true },
    { title: "Metroid Prime 4: Beyond", image: "/metroid4.jpg", platform: "switch2", genres: ["fps", "adventure"], finished: false },
    { title: "Super Mario Wonder", image: "/mario.jpg", platform: "switch", genres: ["platformer"], finished: true },
    { title: "Super Mario Odyssey", image: "/mario.jpg", platform: "switch", genres: ["platformer"], finished: true },
    { title: "Mario Kart 8 Deluxe", image: "/mario.jpg", platform: "switch", genres: ["racing"], finished: true },
    { title: "Splatoon 3", image: "/mario.jpg", platform: "switch", genres: ["shooter"], finished: false },
    { title: "Animal Crossing: New Horizons", image: "/mario.jpg", platform: "switch", genres: ["simulation"], finished: false },
    { title: "Pokémon Scarlet", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: true },
    { title: "Pokémon Violet", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Fire Emblem Engage", image: "/mario.jpg", platform: "switch", genres: ["strategy", "rpg"], finished: false },
    { title: "Xenoblade Chronicles 3", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Kirby and the Forgotten Land", image: "/mario.jpg", platform: "switch", genres: ["platformer"], finished: true },
    { title: "Bayonetta 3", image: "/mario.jpg", platform: "switch", genres: ["action"], finished: false },
    { title: "Astral Chain", image: "/mario.jpg", platform: "switch", genres: ["action"], finished: false },
    { title: "Luigi's Mansion 3", image: "/mario.jpg", platform: "switch", genres: ["adventure"], finished: true },
    { title: "Paper Mario: The Origami King", image: "/mario.jpg", platform: "switch", genres: ["rpg", "adventure"], finished: false },
    { title: "Donkey Kong Country: Tropical Freeze", image: "/mario.jpg", platform: "switch", genres: ["platformer"], finished: false },
    { title: "Yoshi's Crafted World", image: "/mario.jpg", platform: "switch", genres: ["platformer"], finished: false },
    { title: "Pikmin 4", image: "/mario.jpg", platform: "switch", genres: ["strategy"], finished: false },
    { title: "Captain Toad: Treasure Tracker", image: "/mario.jpg", platform: "switch", genres: ["puzzle"], finished: true },
    { title: "Star Fox Zero", image: "/mario.jpg", platform: "switch", genres: ["shooter"], finished: false },
    { title: "Hyrule Warriors: Age of Calamity", image: "/mario.jpg", platform: "switch", genres: ["action"], finished: false },
    { title: "Monster Hunter Rise", image: "/mario.jpg", platform: "switch", genres: ["action", "rpg"], finished: true },
    { title: "Monster Hunter Rise: Sunbreak", image: "/mario.jpg", platform: "switch", genres: ["action", "rpg"], finished: false },
    { title: "Hollow Knight", image: "/mario.jpg", platform: "switch", genres: ["metroidvania"], finished: true },
    { title: "Celeste", image: "/mario.jpg", platform: "switch", genres: ["platformer"], finished: true },
    { title: "Shovel Knight", image: "/mario.jpg", platform: "switch", genres: ["platformer"], finished: false },
    { title: "Cuphead", image: "/mario.jpg", platform: "switch", genres: ["action", "platformer"], finished: false },
    { title: "Undertale", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: true },
    { title: "Stardew Valley", image: "/mario.jpg", platform: "switch", genres: ["simulation", "rpg"], finished: false },
    { title: "Disco Elysium", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Ori and the Blind Forest", image: "/mario.jpg", platform: "switch", genres: ["platformer"], finished: true },
    { title: "Hades", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "action"], finished: true },
    { title: "Dead Cells", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "action"], finished: false },
    { title: "Minecraft", image: "/mario.jpg", platform: "switch", genres: ["sandbox"], finished: false },
    { title: "Terraria", image: "/mario.jpg", platform: "switch", genres: ["sandbox"], finished: false },
    { title: "Doom Eternal", image: "/mario.jpg", platform: "switch", genres: ["fps"], finished: false },
    { title: "The Witcher 3: Wild Hunt", image: "/mario.jpg", platform: "switch", genres: ["rpg", "adventure"], finished: false },
    { title: "Dark Souls Remastered", image: "/mario.jpg", platform: "switch", genres: ["action", "rpg"], finished: false },
    { title: "Octopath Traveler II", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Triangle Strategy", image: "/mario.jpg", platform: "switch", genres: ["strategy", "rpg"], finished: false },
    { title: "Bravely Default II", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Persona 5 Royal", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: true },
    { title: "Persona 4 Golden", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Shin Megami Tensei V", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Dragon Quest XI S", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Ni no Kuni: Wrath of the White Witch", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Ys VIII: Lacrimosa of DANA", image: "/mario.jpg", platform: "switch", genres: ["action", "rpg"], finished: false },
    { title: "Trails of Cold Steel III", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Tales of Vesperia: Definitive Edition", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Xenoblade Chronicles: Definitive Edition", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Final Fantasy XII: The Zodiac Age", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Final Fantasy X/X-2 Remaster", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Chrono Trigger", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Castlevania Anniversary Collection", image: "/mario.jpg", platform: "switch", genres: ["action"], finished: false },
    { title: "Mega Man 11", image: "/mario.jpg", platform: "switch", genres: ["platformer"], finished: false },
    { title: "Sonic Frontiers", image: "/mario.jpg", platform: "switch", genres: ["platformer", "adventure"], finished: false },
    { title: "Sonic Colors Ultimate", image: "/mario.jpg", platform: "switch", genres: ["platformer"], finished: false },
    { title: "Crash Bandicoot 4", image: "/mario.jpg", platform: "switch", genres: ["platformer"], finished: false },
    { title: "Spyro Reignited Trilogy", image: "/mario.jpg", platform: "switch", genres: ["platformer"], finished: false },
    { title: "Rayman Legends", image: "/mario.jpg", platform: "switch", genres: ["platformer"], finished: true },
    { title: "Shovel Knight: Treasure Trove", image: "/mario.jpg", platform: "switch", genres: ["platformer"], finished: false },
    { title: "Axiom Verge 2", image: "/mario.jpg", platform: "switch", genres: ["metroidvania"], finished: false },
    { title: "Metroid Dread", image: "/zelda.jpg", platform: "switch", genres: ["metroidvania"], finished: true },
    { title: "Metroid: Samus Returns", image: "/zelda.jpg", platform: "switch", genres: ["metroidvania"], finished: false },
    { title: "The Legend of Zelda: Tears of the Kingdom", image: "/zelda.jpg", platform: "switch2", genres: ["adventure", "action"], finished: false },
    { title: "The Legend of Zelda: Link's Awakening", image: "/zelda.jpg", platform: "switch", genres: ["adventure"], finished: true },
    { title: "The Legend of Zelda: Skyward Sword HD", image: "/zelda.jpg", platform: "switch", genres: ["adventure", "action"], finished: false },
    { title: "Pikmin 3 Deluxe", image: "/mario.jpg", platform: "switch", genres: ["strategy"], finished: false },
    { title: "Ring Fit Adventure", image: "/mario.jpg", platform: "switch", genres: ["fitness"], finished: false },
    { title: "Nintendo Switch Sports", image: "/mario.jpg", platform: "switch", genres: ["sports"], finished: false },
    { title: "WarioWare: Get It Together!", image: "/mario.jpg", platform: "switch", genres: ["party"], finished: false },
    { title: "Super Smash Bros. Ultimate", image: "/mario.jpg", platform: "switch", genres: ["fighting"], finished: false },
    { title: "Arms", image: "/mario.jpg", platform: "switch", genres: ["fighting"], finished: false },
    { title: "Pokkén Tournament DX", image: "/mario.jpg", platform: "switch", genres: ["fighting"], finished: false },
    { title: "Fitness Boxing 2", image: "/mario.jpg", platform: "switch", genres: ["fitness"], finished: false },
    { title: "Just Dance 2024", image: "/mario.jpg", platform: "switch", genres: ["music"], finished: false },
    { title: "Clubhouse Games: 51 Worldwide Classics", image: "/mario.jpg", platform: "switch", genres: ["party"], finished: false },
    { title: "Overcooked! All You Can Eat", image: "/mario.jpg", platform: "switch", genres: ["co-op"], finished: false },
    { title: "Moving Out", image: "/mario.jpg", platform: "switch", genres: ["co-op"], finished: false },
    { title: "It Takes Two", image: "/mario.jpg", platform: "switch", genres: ["co-op", "adventure"], finished: true },
    { title: "Unravel Two", image: "/mario.jpg", platform: "switch", genres: ["co-op", "platformer"], finished: false },
    { title: "Lovers in a Dangerous Spacetime", image: "/mario.jpg", platform: "switch", genres: ["co-op", "shooter"], finished: false },
    { title: "Enter the Gungeon", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "shooter"], finished: false },
    { title: "Isaac: Afterbirth+", image: "/mario.jpg", platform: "switch", genres: ["roguelike"], finished: false },
    { title: "Slay the Spire", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "card"], finished: false },
    { title: "Into the Breach", image: "/mario.jpg", platform: "switch", genres: ["strategy"], finished: false },
    { title: "Steamworld Dig 2", image: "/mario.jpg", platform: "switch", genres: ["metroidvania"], finished: true },
    { title: "Owlboy", image: "/mario.jpg", platform: "switch", genres: ["platformer", "adventure"], finished: false },
    { title: "Iconoclasts", image: "/mario.jpg", platform: "switch", genres: ["platformer"], finished: false },
    { title: "Golf Story", image: "/mario.jpg", platform: "switch", genres: ["sports", "rpg"], finished: false },
    { title: "Untitled Goose Game", image: "/mario.jpg", platform: "switch", genres: ["puzzle", "comedy"], finished: true },
    { title: "A Short Hike", image: "/mario.jpg", platform: "switch", genres: ["adventure"], finished: true },
    { title: "Night in the Woods", image: "/mario.jpg", platform: "switch", genres: ["adventure"], finished: false },
    { title: "Spiritfarer", image: "/mario.jpg", platform: "switch", genres: ["simulation", "adventure"], finished: false },
    { title: "Chicory: A Colorful Tale", image: "/mario.jpg", platform: "switch", genres: ["adventure", "puzzle"], finished: false },
    { title: "Eastward", image: "/mario.jpg", platform: "switch", genres: ["adventure", "rpg"], finished: false },
    { title: "Turnip Boy Commits Tax Evasion", image: "/mario.jpg", platform: "switch", genres: ["adventure"], finished: true },
    { title: "Hades II", image: "/mario.jpg", platform: "switch2", genres: ["roguelike", "action"], finished: false },
    { title: "Hollow Knight: Silksong", image: "/mario.jpg", platform: "switch2", genres: ["metroidvania"], finished: false },
    { title: "Ori and the Will of the Wisps", image: "/mario.jpg", platform: "switch", genres: ["platformer"], finished: true },
    { title: "Blasphemous 2", image: "/mario.jpg", platform: "switch", genres: ["metroidvania", "action"], finished: false },
    { title: "Salt and Sacrifice", image: "/mario.jpg", platform: "switch", genres: ["action", "rpg"], finished: false },
    { title: "Ender Lilies", image: "/mario.jpg", platform: "switch", genres: ["metroidvania"], finished: false },
    { title: "Nine Sols", image: "/mario.jpg", platform: "switch2", genres: ["metroidvania", "action"], finished: false },
    { title: "Prince of Persia: The Lost Crown", image: "/mario.jpg", platform: "switch", genres: ["metroidvania"], finished: true },
    { title: "Tunic", image: "/mario.jpg", platform: "switch", genres: ["adventure", "action"], finished: false },
    { title: "Outer Wilds", image: "/mario.jpg", platform: "switch", genres: ["adventure", "exploration"], finished: true },
    { title: "Return of the Obra Dinn", image: "/mario.jpg", platform: "switch", genres: ["puzzle", "mystery"], finished: true },
    { title: "Papers, Please", image: "/mario.jpg", platform: "switch", genres: ["simulation", "puzzle"], finished: false },
    { title: "Baba Is You", image: "/mario.jpg", platform: "switch", genres: ["puzzle"], finished: false },
    { title: "The Witness", image: "/mario.jpg", platform: "switch", genres: ["puzzle"], finished: false },
    { title: "Portal", image: "/mario.jpg", platform: "switch", genres: ["puzzle", "fps"], finished: true },
    { title: "Portal 2", image: "/mario.jpg", platform: "switch", genres: ["puzzle", "fps"], finished: true },
    { title: "Superhot", image: "/mario.jpg", platform: "switch", genres: ["fps", "puzzle"], finished: true },
    { title: "Inside", image: "/mario.jpg", platform: "switch", genres: ["platformer", "puzzle"], finished: true },
    { title: "Limbo", image: "/mario.jpg", platform: "switch", genres: ["platformer", "puzzle"], finished: true },
    { title: "Little Nightmares", image: "/mario.jpg", platform: "switch", genres: ["horror", "platformer"], finished: false },
    { title: "Little Nightmares II", image: "/mario.jpg", platform: "switch", genres: ["horror", "platformer"], finished: false },
    { title: "Greak: Memories of Azur", image: "/mario.jpg", platform: "switch", genres: ["platformer", "rpg"], finished: false },
    { title: "Flynn: Son of Crimson", image: "/mario.jpg", platform: "switch", genres: ["platformer", "action"], finished: false },
    { title: "Narita Boy", image: "/mario.jpg", platform: "switch", genres: ["action", "adventure"], finished: false },
    { title: "Cyber Shadow", image: "/mario.jpg", platform: "switch", genres: ["action", "platformer"], finished: false },
    { title: "Neon Abyss", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "platformer"], finished: false },
    { title: "Rogue Legacy 2", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "platformer"], finished: false },
    { title: "Curse of the Dead Gods", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "action"], finished: false },
    { title: "Moonlighter", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "simulation"], finished: false },
    { title: "Crypt of the NecroDancer", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "rhythm"], finished: false },
    { title: "Cadence of Hyrule", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "rhythm"], finished: true },
    { title: "Risk of Rain 2", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "shooter"], finished: false },
    { title: "Gunfire Reborn", image: "/mario.jpg", platform: "switch2", genres: ["roguelike", "fps"], finished: false },
    { title: "Vampire Survivors", image: "/mario.jpg", platform: "switch", genres: ["roguelike"], finished: false },
    { title: "20 Minutes Till Dawn", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "shooter"], finished: false },
    { title: "Brotato", image: "/mario.jpg", platform: "switch", genres: ["roguelike"], finished: false },
    { title: "Dome Keeper", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "strategy"], finished: false },
    { title: "Dicey Dungeons", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "card"], finished: false },
    { title: "Monster Train", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "card"], finished: false },
    { title: "Inscryption", image: "/mario.jpg", platform: "switch2", genres: ["roguelike", "card"], finished: false },
    { title: "Loop Hero", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "strategy"], finished: false },
    { title: "Dungeon of the Endless", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "strategy"], finished: false },
    { title: "One Step From Eden", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "action"], finished: false },
    { title: "Fights in Tight Spaces", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "card"], finished: false },
    { title: "Darkest Dungeon", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "rpg"], finished: false },
    { title: "Darkest Dungeon II", image: "/mario.jpg", platform: "switch2", genres: ["roguelike", "rpg"], finished: false },
    { title: "Children of Morta", image: "/mario.jpg", platform: "switch", genres: ["action", "rpg"], finished: false },
    { title: "Death's Door", image: "/mario.jpg", platform: "switch", genres: ["action", "adventure"], finished: true },
    { title: "Hyper Light Drifter", image: "/mario.jpg", platform: "switch", genres: ["action", "rpg"], finished: false },
    { title: "CrossCode", image: "/mario.jpg", platform: "switch", genres: ["action", "rpg"], finished: false },
    { title: "Eastshade", image: "/mario.jpg", platform: "switch", genres: ["adventure", "exploration"], finished: false },
    { title: "Windbound", image: "/mario.jpg", platform: "switch", genres: ["survival", "adventure"], finished: false },
    { title: "Subnautica", image: "/mario.jpg", platform: "switch", genres: ["survival", "exploration"], finished: false },
    { title: "The Long Dark", image: "/mario.jpg", platform: "switch", genres: ["survival"], finished: false },
    { title: "Valheim", image: "/mario.jpg", platform: "switch2", genres: ["survival", "rpg"], finished: false },
    { title: "Don't Starve Together", image: "/mario.jpg", platform: "switch", genres: ["survival", "co-op"], finished: false },
    { title: "Astroneer", image: "/mario.jpg", platform: "switch", genres: ["sandbox", "exploration"], finished: false },
    { title: "No Man's Sky", image: "/mario.jpg", platform: "switch", genres: ["sandbox", "exploration"], finished: false },
    { title: "Slime Rancher", image: "/mario.jpg", platform: "switch", genres: ["simulation", "sandbox"], finished: false },
    { title: "My Time at Portia", image: "/mario.jpg", platform: "switch", genres: ["simulation", "rpg"], finished: false },
    { title: "Littlewood", image: "/mario.jpg", platform: "switch", genres: ["simulation", "rpg"], finished: false },
    { title: "Wytchwood", image: "/mario.jpg", platform: "switch", genres: ["simulation", "adventure"], finished: false },
    { title: "Coral Island", image: "/mario.jpg", platform: "switch2", genres: ["simulation", "rpg"], finished: false },
    { title: "Sun Haven", image: "/mario.jpg", platform: "switch2", genres: ["simulation", "rpg"], finished: false },
    { title: "Potion Craft", image: "/mario.jpg", platform: "switch", genres: ["simulation"], finished: false },
    { title: "Dorfromantik", image: "/mario.jpg", platform: "switch", genres: ["puzzle", "strategy"], finished: false },
    { title: "Mini Motorways", image: "/mario.jpg", platform: "switch", genres: ["puzzle", "strategy"], finished: false },
    { title: "Mini Metro", image: "/mario.jpg", platform: "switch", genres: ["puzzle", "strategy"], finished: false },
    { title: "Townscaper", image: "/mario.jpg", platform: "switch", genres: ["sandbox"], finished: false },
    { title: "Alba: A Wildlife Adventure", image: "/mario.jpg", platform: "switch", genres: ["adventure"], finished: true },
    { title: "Unpacking", image: "/mario.jpg", platform: "switch", genres: ["puzzle", "simulation"], finished: true },
    { title: "Nour: Play With Your Food", image: "/mario.jpg", platform: "switch2", genres: ["sandbox"], finished: false },
    { title: "Toem", image: "/mario.jpg", platform: "switch", genres: ["adventure"], finished: true },
    { title: "Gris", image: "/mario.jpg", platform: "switch", genres: ["platformer", "art"], finished: true },
    { title: "Journey", image: "/mario.jpg", platform: "switch2", genres: ["adventure", "art"], finished: true },
    { title: "Abzû", image: "/mario.jpg", platform: "switch", genres: ["adventure", "art"], finished: true },
    { title: "Flower", image: "/mario.jpg", platform: "switch", genres: ["art", "relaxing"], finished: true },
    { title: "Everything", image: "/mario.jpg", platform: "switch", genres: ["simulation", "art"], finished: false },
    { title: "What Remains of Edith Finch", image: "/mario.jpg", platform: "switch", genres: ["adventure", "narrative"], finished: true },
    { title: "Firewatch", image: "/mario.jpg", platform: "switch", genres: ["adventure", "narrative"], finished: true },
    { title: "Oxenfree", image: "/mario.jpg", platform: "switch", genres: ["adventure", "narrative"], finished: false },
    { title: "Oxenfree II: Lost Signals", image: "/mario.jpg", platform: "switch", genres: ["adventure", "narrative"], finished: false },
    { title: "Tacoma", image: "/mario.jpg", platform: "switch", genres: ["adventure", "narrative"], finished: false },
    { title: "Telling Lies", image: "/mario.jpg", platform: "switch", genres: ["mystery", "narrative"], finished: false },
    { title: "Heaven's Vault", image: "/mario.jpg", platform: "switch", genres: ["adventure", "narrative"], finished: false },
    { title: "Elsinore", image: "/mario.jpg", platform: "switch", genres: ["adventure", "narrative"], finished: false },
    { title: "Pentiment", image: "/mario.jpg", platform: "switch2", genres: ["narrative", "adventure"], finished: false },
    { title: "Disco Elysium: Final Cut", image: "/mario.jpg", platform: "switch", genres: ["rpg", "narrative"], finished: false },
    { title: "Citizen Sleeper", image: "/mario.jpg", platform: "switch", genres: ["rpg", "narrative"], finished: false },
    { title: "Norco", image: "/mario.jpg", platform: "switch", genres: ["adventure", "narrative"], finished: false },
    { title: "Hardspace: Shipbreaker", image: "/mario.jpg", platform: "switch2", genres: ["simulation"], finished: false },
    { title: "PowerWash Simulator", image: "/mario.jpg", platform: "switch", genres: ["simulation"], finished: false },
    { title: "Lawn Mowing Simulator", image: "/mario.jpg", platform: "switch", genres: ["simulation"], finished: false },
    { title: "Cooking Simulator", image: "/mario.jpg", platform: "switch", genres: ["simulation"], finished: false },
    { title: "Car Mechanic Simulator", image: "/mario.jpg", platform: "switch", genres: ["simulation"], finished: false },
    { title: "PC Building Simulator", image: "/mario.jpg", platform: "switch", genres: ["simulation"], finished: false },
    { title: "Two Point Hospital", image: "/mario.jpg", platform: "switch", genres: ["simulation", "strategy"], finished: false },
    { title: "Two Point Campus", image: "/mario.jpg", platform: "switch", genres: ["simulation", "strategy"], finished: false },
    { title: "Cities: Skylines", image: "/mario.jpg", platform: "switch", genres: ["simulation", "strategy"], finished: false },
    { title: "Surviving Mars", image: "/mario.jpg", platform: "switch", genres: ["simulation", "strategy"], finished: false },
    { title: "Tropico 6", image: "/mario.jpg", platform: "switch", genres: ["simulation", "strategy"], finished: false },
    { title: "Civilization VI", image: "/mario.jpg", platform: "switch", genres: ["strategy"], finished: false },
    { title: "XCOM 2 Collection", image: "/mario.jpg", platform: "switch", genres: ["strategy", "rpg"], finished: false },
    { title: "Mario + Rabbids Kingdom Battle", image: "/mario.jpg", platform: "switch", genres: ["strategy"], finished: true },
    { title: "Mario + Rabbids Sparks of Hope", image: "/mario.jpg", platform: "switch", genres: ["strategy"], finished: false },
    { title: "Advance Wars 1+2", image: "/mario.jpg", platform: "switch", genres: ["strategy"], finished: false },
    { title: "Wargroove", image: "/mario.jpg", platform: "switch", genres: ["strategy"], finished: false },
    { title: "Wargroove 2", image: "/mario.jpg", platform: "switch", genres: ["strategy"], finished: false },
    { title: "Thronefall", image: "/mario.jpg", platform: "switch2", genres: ["strategy"], finished: false },
    { title: "Kingdom Two Crowns", image: "/mario.jpg", platform: "switch", genres: ["strategy", "survival"], finished: false },
    { title: "Northgard", image: "/mario.jpg", platform: "switch", genres: ["strategy", "survival"], finished: false },
    { title: "Bad North", image: "/mario.jpg", platform: "switch", genres: ["strategy"], finished: false },
    { title: "Tiny Metal: Full Metal Rumble", image: "/mario.jpg", platform: "switch", genres: ["strategy"], finished: false },
    { title: "Tactical Nexus", image: "/mario.jpg", platform: "switch2", genres: ["strategy", "puzzle"], finished: false },
    { title: "Invisible Inc.", image: "/mario.jpg", platform: "switch", genres: ["strategy", "stealth"], finished: false },
    { title: "Frozen Synapse", image: "/mario.jpg", platform: "switch", genres: ["strategy"], finished: false },
    { title: "Divinity: Original Sin 2", image: "/mario.jpg", platform: "switch", genres: ["rpg", "strategy"], finished: false },
    { title: "Pillars of Eternity: Complete Edition", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Torment: Tides of Numenera", image: "/mario.jpg", platform: "switch", genres: ["rpg", "narrative"], finished: false },
    { title: "Baldur's Gate: Enhanced Edition", image: "/mario.jpg", platform: "switch", genres: ["rpg", "strategy"], finished: false },
    { title: "Planescape: Torment", image: "/mario.jpg", platform: "switch", genres: ["rpg", "narrative"], finished: false },
    { title: "Neverwinter Nights: Enhanced Edition", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Pathfinder: Kingmaker", image: "/mario.jpg", platform: "switch", genres: ["rpg", "strategy"], finished: false },
    { title: "Wasteland 3", image: "/mario.jpg", platform: "switch", genres: ["rpg", "strategy"], finished: false },
    { title: "Solasta: Crown of the Magister", image: "/mario.jpg", platform: "switch2", genres: ["rpg", "strategy"], finished: false },
    { title: "Lost Ruins", image: "/mario.jpg", platform: "switch", genres: ["action", "rpg"], finished: false },
    { title: "Momodora: Moonlit Farewell", image: "/mario.jpg", platform: "switch2", genres: ["action", "platformer"], finished: false },
    { title: "Record of Lodoss War: Deedlit in Wonder Labyrinth", image: "/mario.jpg", platform: "switch", genres: ["metroidvania"], finished: false },
    { title: "Souldiers", image: "/mario.jpg", platform: "switch", genres: ["metroidvania", "rpg"], finished: false },
    { title: "Alwa's Legacy", image: "/mario.jpg", platform: "switch", genres: ["metroidvania"], finished: false },
    { title: "Haiku the Robot", image: "/mario.jpg", platform: "switch", genres: ["metroidvania"], finished: false },
    { title: "Teslagrad 2", image: "/mario.jpg", platform: "switch", genres: ["metroidvania", "puzzle"], finished: false },
    { title: "Gestalt: Steam & Cinder", image: "/mario.jpg", platform: "switch2", genres: ["metroidvania", "action"], finished: false },
    { title: "Rise of the Ronin", image: "/mario.jpg", platform: "switch2", genres: ["action", "rpg"], finished: false },
    { title: "Ghost of Tsushima: Director's Cut", image: "/mario.jpg", platform: "switch2", genres: ["action", "adventure"], finished: false },
    { title: "Assassin's Creed: Shadows", image: "/mario.jpg", platform: "switch2", genres: ["action", "adventure"], finished: false },
    { title: "Cyberpunk 2077", image: "/mario.jpg", platform: "switch2", genres: ["rpg", "fps"], finished: false },
    { title: "Elden Ring", image: "/mario.jpg", platform: "switch2", genres: ["action", "rpg"], finished: false },
    { title: "Bloodborne", image: "/mario.jpg", platform: "switch2", genres: ["action", "rpg"], finished: false },
    { title: "Sekiro: Shadows Die Twice", image: "/mario.jpg", platform: "switch2", genres: ["action"], finished: false },
    { title: "Lies of P", image: "/mario.jpg", platform: "switch2", genres: ["action", "rpg"], finished: false },
    { title: "Lords of the Fallen", image: "/mario.jpg", platform: "switch2", genres: ["action", "rpg"], finished: false },
    { title: "Remnant: From the Ashes", image: "/mario.jpg", platform: "switch2", genres: ["action", "shooter"], finished: false },
    { title: "Remnant II", image: "/mario.jpg", platform: "switch2", genres: ["action", "shooter"], finished: false },
    { title: "Nioh 2", image: "/mario.jpg", platform: "switch2", genres: ["action", "rpg"], finished: false },
    { title: "Wo Long: Fallen Dynasty", image: "/mario.jpg", platform: "switch2", genres: ["action", "rpg"], finished: false },
    { title: "Star Wars Jedi: Survivor", image: "/mario.jpg", platform: "switch2", genres: ["action", "adventure"], finished: false },
    { title: "Star Wars Jedi: Fallen Order", image: "/mario.jpg", platform: "switch2", genres: ["action", "adventure"], finished: false },
    { title: "Batman: Arkham Knight", image: "/mario.jpg", platform: "switch2", genres: ["action", "adventure"], finished: false },
    { title: "Spider-Man: Miles Morales", image: "/mario.jpg", platform: "switch2", genres: ["action", "adventure"], finished: false },
    { title: "Marvel's Spider-Man 2", image: "/mario.jpg", platform: "switch2", genres: ["action", "adventure"], finished: false },
    { title: "God of War", image: "/mario.jpg", platform: "switch2", genres: ["action", "adventure"], finished: false },
    { title: "God of War Ragnarök", image: "/mario.jpg", platform: "switch2", genres: ["action", "adventure"], finished: false },
    { title: "Horizon Zero Dawn", image: "/mario.jpg", platform: "switch2", genres: ["action", "rpg"], finished: false },
    { title: "Horizon Forbidden West", image: "/mario.jpg", platform: "switch2", genres: ["action", "rpg"], finished: false },
    { title: "The Last of Us Part I", image: "/mario.jpg", platform: "switch2", genres: ["action", "adventure"], finished: false },
    { title: "The Last of Us Part II", image: "/mario.jpg", platform: "switch2", genres: ["action", "adventure"], finished: false },
    { title: "Death Stranding", image: "/mario.jpg", platform: "switch2", genres: ["action", "adventure"], finished: false },
    { title: "Control", image: "/mario.jpg", platform: "switch2", genres: ["action", "adventure"], finished: false },
    { title: "Alan Wake 2", image: "/mario.jpg", platform: "switch2", genres: ["action", "horror"], finished: false },
    { title: "Resident Evil 4 Remake", image: "/mario.jpg", platform: "switch2", genres: ["action", "horror"], finished: true },
    { title: "Resident Evil Village", image: "/mario.jpg", platform: "switch2", genres: ["action", "horror"], finished: false },
    { title: "Resident Evil 2 Remake", image: "/mario.jpg", platform: "switch2", genres: ["action", "horror"], finished: false },
    { title: "Silent Hill 2 Remake", image: "/mario.jpg", platform: "switch2", genres: ["horror", "adventure"], finished: false },
    { title: "Returnal", image: "/mario.jpg", platform: "switch2", genres: ["roguelike", "shooter"], finished: false },
    { title: "Deathloop", image: "/mario.jpg", platform: "switch2", genres: ["fps", "action"], finished: false },
    { title: "Prey", image: "/mario.jpg", platform: "switch2", genres: ["fps", "rpg"], finished: false },
    { title: "Dishonored 2", image: "/mario.jpg", platform: "switch2", genres: ["fps", "stealth"], finished: false },
    { title: "Deus Ex: Mankind Divided", image: "/mario.jpg", platform: "switch2", genres: ["fps", "rpg"], finished: false },
    { title: "BioShock Infinite", image: "/mario.jpg", platform: "switch", genres: ["fps", "action"], finished: true },
    { title: "BioShock: The Collection", image: "/mario.jpg", platform: "switch", genres: ["fps", "action"], finished: false },
    { title: "Borderlands 3", image: "/mario.jpg", platform: "switch", genres: ["fps", "rpg"], finished: false },
    { title: "Tiny Tina's Wonderlands", image: "/mario.jpg", platform: "switch2", genres: ["fps", "rpg"], finished: false },
    { title: "Outriders", image: "/mario.jpg", platform: "switch2", genres: ["shooter", "rpg"], finished: false },
    { title: "Warframe", image: "/mario.jpg", platform: "switch", genres: ["shooter", "rpg"], finished: false },
    { title: "Payday 3", image: "/mario.jpg", platform: "switch2", genres: ["shooter", "co-op"], finished: false },
    { title: "Helldivers 2", image: "/mario.jpg", platform: "switch2", genres: ["shooter", "co-op"], finished: false },
    { title: "Deep Rock Galactic", image: "/mario.jpg", platform: "switch2", genres: ["shooter", "co-op"], finished: false },
    { title: "Back 4 Blood", image: "/mario.jpg", platform: "switch2", genres: ["shooter", "co-op"], finished: false },
    { title: "Aliens: Fireteam Elite", image: "/mario.jpg", platform: "switch2", genres: ["shooter", "co-op"], finished: false },
    { title: "Fortnite", image: "/mario.jpg", platform: "switch", genres: ["battle royale", "shooter"], finished: false },
    { title: "Apex Legends", image: "/mario.jpg", platform: "switch", genres: ["battle royale", "shooter"], finished: false },
    { title: "Fall Guys", image: "/mario.jpg", platform: "switch", genres: ["battle royale", "party"], finished: false },
    { title: "Among Us", image: "/mario.jpg", platform: "switch", genres: ["party", "social"], finished: false },
    { title: "Pummel Party", image: "/mario.jpg", platform: "switch", genres: ["party", "co-op"], finished: false },
    { title: "Jackbox Party Pack 9", image: "/mario.jpg", platform: "switch", genres: ["party"], finished: false },
    { title: "Boomerang Fu", image: "/mario.jpg", platform: "switch", genres: ["party", "action"], finished: false },
    { title: "Nidhogg 2", image: "/mario.jpg", platform: "switch", genres: ["fighting", "party"], finished: false },
    { title: "Towerfall Ascension", image: "/mario.jpg", platform: "switch", genres: ["party", "action"], finished: false },
    { title: "Samurai Gunn 2", image: "/mario.jpg", platform: "switch", genres: ["party", "action"], finished: false },
    { title: "Killer Queen Black", image: "/mario.jpg", platform: "switch", genres: ["party", "strategy"], finished: false },
    { title: "Ultimate Chicken Horse", image: "/mario.jpg", platform: "switch", genres: ["party", "platformer"], finished: false },
    { title: "Spelunky 2", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "platformer"], finished: false },
    { title: "Spelunky Classic", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "platformer"], finished: false },
    { title: "Downwell", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "platformer"], finished: false },
    { title: "UFO 50", image: "/mario.jpg", platform: "switch2", genres: ["anthology"], finished: false },
    { title: "Balatro", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "card"], finished: false },
    { title: "Luck be a Landlord", image: "/mario.jpg", platform: "switch2", genres: ["roguelike"], finished: false },
    { title: "Cobalt Core", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "card"], finished: false },
    { title: "Slice & Dice", image: "/mario.jpg", platform: "switch2", genres: ["roguelike", "card"], finished: false },
    { title: "Peglin", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "puzzle"], finished: false },
    { title: "Across the Obelisk", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "card"], finished: false },
    { title: "Gordian Quest", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "card"], finished: false },
    { title: "Griftlands", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "card"], finished: false },
    { title: "Night of the Full Moon", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "card"], finished: false },
    { title: "Roguebook", image: "/mario.jpg", platform: "switch", genres: ["roguelike", "card"], finished: false },
    { title: "Monster Sanctuary", image: "/mario.jpg", platform: "switch", genres: ["rpg", "metroidvania"], finished: false },
    { title: "Coromon", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Cassette Beasts", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Temtem", image: "/mario.jpg", platform: "switch", genres: ["rpg", "mmo"], finished: false },
    { title: "World of Final Fantasy", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Final Fantasy I-VI Pixel Remaster", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Final Fantasy VII Remake", image: "/mario.jpg", platform: "switch2", genres: ["action", "rpg"], finished: false },
    { title: "Final Fantasy XVI", image: "/mario.jpg", platform: "switch2", genres: ["action", "rpg"], finished: false },
    { title: "Crisis Core: Final Fantasy VII Reunion", image: "/mario.jpg", platform: "switch", genres: ["action", "rpg"], finished: false },
    { title: "Dragon Quest Monsters: The Dark Prince", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Dragon Quest Treasures", image: "/mario.jpg", platform: "switch", genres: ["rpg", "adventure"], finished: false },
    { title: "Dragon Quest Heroes", image: "/mario.jpg", platform: "switch", genres: ["action", "rpg"], finished: false },
    { title: "Atelier Ryza 3", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Atelier Sophie 2", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Blue Reflection: Second Light", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Fairy Fencer F: Refrain Chord", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Neptunia Game Maker R:Evolution", image: "/mario.jpg", platform: "switch2", genres: ["rpg"], finished: false },
    { title: "Disgaea 7", image: "/mario.jpg", platform: "switch", genres: ["strategy", "rpg"], finished: false },
    { title: "Disgaea 6 Complete", image: "/mario.jpg", platform: "switch", genres: ["strategy", "rpg"], finished: false },
    { title: "Tactics Ogre: Reborn", image: "/mario.jpg", platform: "switch", genres: ["strategy", "rpg"], finished: false },
    { title: "Fire Emblem: Three Houses", image: "/mario.jpg", platform: "switch", genres: ["strategy", "rpg"], finished: true },
    { title: "Fire Emblem Warriors: Three Hopes", image: "/mario.jpg", platform: "switch", genres: ["action"], finished: false },
    { title: "Tokyo Mirage Sessions #FE Encore", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Xenoblade Chronicles 2", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Xenoblade Chronicles X: Definitive Edition", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Trails from Zero", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Trails to Azure", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Trails into Reverie", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Ys IX: Monstrum Nox", image: "/mario.jpg", platform: "switch", genres: ["action", "rpg"], finished: false },
    { title: "The Legend of Heroes: Hajimari no Kiseki", image: "/mario.jpg", platform: "switch", genres: ["rpg"], finished: false },
    { title: "Rune Factory 5", image: "/mario.jpg", platform: "switch", genres: ["simulation", "rpg"], finished: false },
    { title: "Rune Factory 4 Special", image: "/mario.jpg", platform: "switch", genres: ["simulation", "rpg"], finished: false },
    { title: "Story of Seasons: A Wonderful Life", image: "/mario.jpg", platform: "switch", genres: ["simulation"], finished: false },
    { title: "Harvest Moon: The Winds of Anthos", image: "/mario.jpg", platform: "switch", genres: ["simulation"], finished: false },
    { title: "Poké Park 2", image: "/mario.jpg", platform: "switch", genres: ["adventure"], finished: false },
    { title: "Pokémon Legends: Arceus", image: "/mario.jpg", platform: "switch", genres: ["rpg", "action"], finished: true },
    { title: "Pokémon Legends: Z-A", image: "/mario.jpg", platform: "switch2", genres: ["rpg", "action"], finished: false },
    { title: "Pokémon Mystery Dungeon: Rescue Team DX", image: "/mario.jpg", platform: "switch", genres: ["rpg", "roguelike"], finished: false },
    { title: "Pokémon Snap", image: "/mario.jpg", platform: "switch", genres: ["adventure", "photography"], finished: false },
    { title: "Kirby's Return to Dream Land Deluxe", image: "/mario.jpg", platform: "switch", genres: ["platformer"], finished: false },
    { title: "Kirby's Dream Buffet", image: "/mario.jpg", platform: "switch", genres: ["party"], finished: false },
    { title: "Kirby: Star Allies", image: "/mario.jpg", platform: "switch", genres: ["platformer"], finished: false },
    { title: "Wario Land: Shake It!", image: "/mario.jpg", platform: "switch", genres: ["platformer"], finished: false },
    { title: "Super Mario 3D World + Bowser's Fury", image: "/mario.jpg", platform: "switch", genres: ["platformer"], finished: true },
    { title: "Super Mario 3D All-Stars", image: "/mario.jpg", platform: "switch", genres: ["platformer"], finished: false },
    { title: "Super Mario Bros. Wonder", image: "/mario.jpg", platform: "switch", genres: ["platformer"], finished: false },
    { title: "New Super Mario Bros. U Deluxe", image: "/mario.jpg", platform: "switch", genres: ["platformer"], finished: false },
    { title: "Mario Party Superstars", image: "/mario.jpg", platform: "switch", genres: ["party"], finished: false },
    { title: "Super Mario Party Jamboree", image: "/mario.jpg", platform: "switch2", genres: ["party"], finished: false },
    { title: "Mario Golf: Super Rush", image: "/mario.jpg", platform: "switch", genres: ["sports"], finished: false },
    { title: "Mario Strikers: Battle League", image: "/mario.jpg", platform: "switch", genres: ["sports"], finished: false },
    { title: "Mario Tennis Aces", image: "/mario.jpg", platform: "switch", genres: ["sports"], finished: false },
    { title: "F-Zero 99", image: "/mario.jpg", platform: "switch", genres: ["racing"], finished: false },
    { title: "Burnout Paradise Remastered", image: "/mario.jpg", platform: "switch", genres: ["racing"], finished: false },
    { title: "Crash Team Racing Nitro-Fueled", image: "/mario.jpg", platform: "switch", genres: ["racing"], finished: false },
    { title: "Team Sonic Racing", image: "/mario.jpg", platform: "switch", genres: ["racing"], finished: false },
    { title: "Garfield Kart: Furious Racing", image: "/mario.jpg", platform: "switch", genres: ["racing"], finished: false },
    { title: "Hot Wheels Unleashed 2", image: "/mario.jpg", platform: "switch", genres: ["racing"], finished: false },
    { title: "GRID Autosport", image: "/mario.jpg", platform: "switch", genres: ["racing"], finished: false },
    { title: "Gear.Club Unlimited 2", image: "/mario.jpg", platform: "switch", genres: ["racing"], finished: false },
    { title: "Instant Sports Summer Games", image: "/mario.jpg", platform: "switch", genres: ["sports"], finished: false },
    { title: "Olympic Games Tokyo 2020", image: "/mario.jpg", platform: "switch", genres: ["sports"], finished: false },
    { title: "Knockout City", image: "/mario.jpg", platform: "switch", genres: ["sports", "action"], finished: false },
    { title: "Rocket League Sideswipe", image: "/mario.jpg", platform: "switch", genres: ["sports", "action"], finished: false },
    { title: "Windjammers 2", image: "/mario.jpg", platform: "switch", genres: ["sports", "action"], finished: false },
    { title: "Sociable Soccer 24", image: "/mario.jpg", platform: "switch2", genres: ["sports"], finished: false },
  ];

  return (
    <div className="app">
      <Shelf
        games={games}
        openGame={openGame}
        onSetOpenGame={setOpenGame}
      />
    </div>
  );
};

export default App;    